// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5O_jAv6xX1nUKmknDuwvUBhz-RqPwo1w',
    appId: '1:256920318665:web:8a108acd37e92b6c261318',
    messagingSenderId: '256920318665',
    projectId: 'saloon-blue-f7c93',
    authDomain: 'saloon-blue-f7c93.firebaseapp.com',
    storageBucket: 'saloon-blue-f7c93.firebasestorage.app',
    measurementId: 'G-BPPNB843R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcDhZ2QTit0OtnayqbvI52btZ3K98sPwU',
    appId: '1:256920318665:android:93c358c4bd668e57261318',
    messagingSenderId: '256920318665',
    projectId: 'saloon-blue-f7c93',
    storageBucket: 'saloon-blue-f7c93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6JZQu8SApQNvkSc4BaR3kiSsYu_QyR3o',
    appId: '1:256920318665:ios:1aa9b1b1a60ba905261318',
    messagingSenderId: '256920318665',
    projectId: 'saloon-blue-f7c93',
    storageBucket: 'saloon-blue-f7c93.firebasestorage.app',
    iosBundleId: 'com.example.saloonAppointmentBookingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6JZQu8SApQNvkSc4BaR3kiSsYu_QyR3o',
    appId: '1:256920318665:ios:1aa9b1b1a60ba905261318',
    messagingSenderId: '256920318665',
    projectId: 'saloon-blue-f7c93',
    storageBucket: 'saloon-blue-f7c93.firebasestorage.app',
    iosBundleId: 'com.example.saloonAppointmentBookingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5O_jAv6xX1nUKmknDuwvUBhz-RqPwo1w',
    appId: '1:256920318665:web:ccb54ca57ed61c4e261318',
    messagingSenderId: '256920318665',
    projectId: 'saloon-blue-f7c93',
    authDomain: 'saloon-blue-f7c93.firebaseapp.com',
    storageBucket: 'saloon-blue-f7c93.firebasestorage.app',
    measurementId: 'G-5JCBB9SBS9',
  );
}
